randnumgen/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^_ah/', include('djangae.urls')),
    url(r'^', include('rng.urls', namespace="rng")),
]

rng/urls.py
from django.conf.urls import url

from . import views

app_name = "rng"
urlpatterns = [
    url(r'rng/?$', views.random_number_generator, name="rng"),
    url(r'used/?$', views.usedindex, name="index"),
    url(r'^$', views.hpv, name="hp"),
]

rng/models.py
from django.db import models
from djangae import fields

import random
import functools

_RINT = functools.partial(random.SystemRandom().randint, 0)
_PRIME = 2 ** 127 - 1

class UsedNumber(models.Model):
    number = fields.CharField()

    def __str__(self):
        return self.number

    @classmethod
    def new(cls):
        r = str(_RINT(_PRIME))
        x, c = cls.objects.get_or_create(
            number = r,
            defaults = {
                'number': r
            },
        )
        if c:
            x.save()
        return x

rng/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.base import TemplateView
from django.views import generic

from .models import UsedNumber

def random_number_generator(request):
    rand = UsedNumber.new()
    return HttpResponse(rand.number, content_type="text/plain")

class HomePageView(TemplateView):
    template_name = "rng/random.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['random'] = UsedNumber.new().number
        return context

hpv = HomePageView.as_view()

class UsedList(generic.ListView):
    model = UsedNumber
    template_name = "rng/list.html"

usedindex = UsedList.as_view()

rng/templates/rng/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}A random number{% endblock %}</title>
	</head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<style>
	div {
		text-align: center;
		margin-top: 25%;
	}
	footer {
		position: fixed;
		font-size: 14px;
		bottom: 14px;
		right: 14px;
	}
	</style>
	<body>
		{% block container %}
		<div>
			<code>{{ random }}</code>
		</div>
		{% endblock %}
		<footer>
			<a href="{% url 'rng:hp' %}">home</a>
			<a href="{% url 'rng:rng' %}">api</a>
			<a href="{% url 'rng:index' %}">list</a>
			<a href="https://github.com/0xdc/gae-rng" target="_blank">source</a>
		</footer>
		{% block script %}
		{% endblock %}
	</body>
</html>

rng/templates/rng/list.html
{% extends 'rng/base.html' %}
{% block container %}
<ul>
{% for used in usednumber_list %}
<li><code>{{ used.number }}</code></li>
{% endfor %}
</ul>
{% endblock %}

rng/templates/rng/random.html
{% extends 'rng/base.html' %}
{% block container %}
<div>
	<code>{{ random }}</code>
</div>
{% endblock %}
{% block script %}
<script>
	code = document.querySelector("code");
	loop = null;
	fetch_and_update = function() {
		clearInterval(loop);
		fetch("{% url 'rng:rng' %}")
			.then(a=>{return a.text()})
			.then(b=>{code.innerText = b})
		loop = setInterval(fetch_and_update, 30000);
	}
	window.onload = function() {
		loop = setInterval(fetch_and_update, 30000);
	}
</script>
{% endblock %}